# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LoopBannerView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod "YYWebImage"
  # Pods for LoopBannerView

  target 'LoopBannerViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoopBannerViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
